/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.aregister.gui.dialog.au;

import com.aldrin.aregister.dao.impl.RoomDAOImpl;
import com.aldrin.aregister.gui.JFrameRegister;
import com.aldrin.aregister.model.Room;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogRoomAU extends javax.swing.JDialog {


    private JFrameRegister jFrameRegister;
    private Room room = new Room();
    static String title;
    private RoomDAOImpl courseDAOImpl = new RoomDAOImpl();

    public JDialogRoomAU(JFrameRegister jFrameRegister, boolean modal) {
        super(jFrameRegister, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldRoom.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ROOM");
        jTextFieldLocation.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "LOCATION");
        jTextFieldRoom.setText(room.getRoom());
        jTextFieldLocation.setText(room.getLocation());

    }

    public JDialogRoomAU(JFrameRegister jFrameRegister, boolean modal, Room room, String title) {
        super(jFrameRegister, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.title = title;
        this.room = room;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldRoom.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ROOM");
        jTextFieldLocation.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "LOCATION");
        jTextFieldRoom.setText(room.getRoom());
        jTextFieldLocation.setText(room.getLocation());
    }

    public JDialogRoomAU(JFrameRegister jFrameRegister, boolean modal, String title, Room room) {
        super(jFrameRegister, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.room = room;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldRoom.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "COURSE");
        jTextFieldLocation.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ACRONYM");
        jTextFieldRoom.setText(room.getRoom());
        jTextFieldLocation.setText(room.getLocation());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jTextFieldRoom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ROOM:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 80, 30));
        getContentPane().add(jTextFieldLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, 30));
        getContentPane().add(jTextFieldRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("LOCATION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 80, 30));

        setSize(new java.awt.Dimension(366, 203));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to save " + jTextFieldRoom.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.room.setId(null);
                this.room.setRoom(jTextFieldRoom.getText());
                this.room.setLocation(jTextFieldLocation.getText());
                courseDAOImpl.addRoom(room);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to update " + jTextFieldRoom.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.room.setRoom(jTextFieldRoom.getText());
                this.room.setLocation(jTextFieldLocation.getText());
                courseDAOImpl.updateRoom(room);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to delete " + jTextFieldRoom.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                courseDAOImpl.deleteRoom(room);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldRoom;
    // End of variables declaration//GEN-END:variables
}
