/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.aregister.gui.dialog.au;

import com.aldrin.aregister.dao.impl.SubjectDAOImpl;
import com.aldrin.aregister.gui.JFrameRegister;
import com.aldrin.aregister.model.Subject;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogSubjectAU extends javax.swing.JDialog {


    private JFrameRegister jFrameRegister;
    private Subject subject = new Subject();
    static String title;
    private SubjectDAOImpl courseDAOImpl = new SubjectDAOImpl();

    public JDialogSubjectAU(JFrameRegister jFrameRegister, boolean modal) {
        super(jFrameRegister, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
  
        jTextFieldCode.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CODE");
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");

    }

    public JDialogSubjectAU(JFrameRegister jFrameRegister, boolean modal, Subject subject, String title) {
        super(jFrameRegister, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.title = title;
        this.subject = subject;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldCode.setText(subject.getCode());
        jTextFieldSubject.setText(subject.getSubject());
        jTextFieldUnit.setText(String.valueOf(subject.getUnit()));
        jTextFieldCode.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CODE");
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");
    }

    public JDialogSubjectAU(JFrameRegister jFrameRegister, boolean modal, String title, Subject subject) {
        super(jFrameRegister, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.subject = subject;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldCode.setText(subject.getCode());
        jTextFieldSubject.setText(subject.getSubject());
        jTextFieldUnit.setText(String.valueOf(subject.getUnit()));
        jTextFieldCode.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CODE");
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUnit = new javax.swing.JTextField();
        jTextFieldCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSubject = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("CODE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 80, 30));
        getContentPane().add(jTextFieldUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, 30));
        getContentPane().add(jTextFieldCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("UNIT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 80, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SUBJECT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 80, 30));
        getContentPane().add(jTextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, 30));

        setSize(new java.awt.Dimension(366, 239));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to save " + jTextFieldCode.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.subject.setId(null);
                this.subject.setCode(jTextFieldCode.getText());
                this.subject.setSubject(jTextFieldSubject.getText());
                this.subject.setUnit(Integer.parseInt(jTextFieldUnit.getText()));
                courseDAOImpl.addSubject(subject);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to update " + jTextFieldCode.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.subject.setCode(jTextFieldCode.getText());
                this.subject.setSubject(jTextFieldSubject.getText());
                this.subject.setUnit(Integer.parseInt(jTextFieldUnit.getText()));
                courseDAOImpl.updateSubject(subject);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to delete " + jTextFieldCode.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                courseDAOImpl.deleteSubject(subject);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextFieldUnit;
    // End of variables declaration//GEN-END:variables
}
