/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.aregister.gui;

import com.aldrin.aregister.controller.AppController;
import com.aldrin.aregister.dao.impl.ClassEnrollDAOImpl;
import com.aldrin.aregister.dao.impl.ClassOfferDAOImpl;
import com.aldrin.aregister.dao.impl.SchoolYearDAOImpl;
import com.aldrin.aregister.gui.dialog.JDialogChangePassword;
import com.aldrin.aregister.gui.dialog.JDialogCitizenship;
import com.aldrin.aregister.gui.dialog.JDialogClassOffer;
import com.aldrin.aregister.gui.dialog.JDialogCourse;
import com.aldrin.aregister.gui.dialog.JDialogDay;
import com.aldrin.aregister.gui.dialog.JDialogEnrolledStudents;
import com.aldrin.aregister.gui.dialog.JDialogInstructor;
import com.aldrin.aregister.gui.dialog.JDialogInstructorSubjects;
import com.aldrin.aregister.gui.dialog.JDialogRole;
import com.aldrin.aregister.gui.dialog.JDialogRoom;
import com.aldrin.aregister.gui.dialog.JDialogSchoolYear;
import com.aldrin.aregister.gui.dialog.JDialogSchoolYearTuition;
import com.aldrin.aregister.gui.dialog.JDialogSemester;
import com.aldrin.aregister.gui.dialog.JDialogStudent;
import com.aldrin.aregister.gui.dialog.JDialogSubject;
import com.aldrin.aregister.gui.dialog.JDialogTime;
import com.aldrin.aregister.gui.dialog.JDialogTuition;
import com.aldrin.aregister.gui.dialog.JDialogUserAccount;
import com.aldrin.aregister.gui.dialog.report.JDialogReportCOR;
import com.aldrin.aregister.gui.dialog.report.JDialogReportClassOffer;
import com.aldrin.aregister.gui.dialog.report.JDialogReportInstructor;
import com.aldrin.aregister.model.ClassEnroll;
import com.aldrin.aregister.model.SchoolYear;
import com.aldrin.aregister.model.UserAccount;
import com.aldrin.aregister.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author ALRIN B.C.
 */
@Setter
@Getter
public class JFrameRegister extends javax.swing.JFrame implements MouseListener, ActionListener {

    /**
     * Creates new form JFrameRegister
     */
    private SchoolYearDAOImpl schoolYearDAOImpl = new SchoolYearDAOImpl();
    private ClassEnrollDAOImpl classEnrollDAOImpl = new ClassEnrollDAOImpl();
    private DecimalFormat df = new DecimalFormat("##,##0.00");
    private UserAccount userAccount;
    public static UserAccount userLogin;
    private ClassOfferDAOImpl classOfferDAOImpl = new ClassOfferDAOImpl();

    public JFrameRegister() {
        initComponents();
        FlatSVGIcon icon = new FlatSVGIcon("svg/app.svg");
        setIconImage(icon.getImage());
        setTitle("ARegister v1.0.0");
        setTable();
        jTextFieldSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search");
        jTextFieldSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("svg/search.svg", 24, 24));
        comboBoxSchoolYear();
        jComboBoxSchoolYear.addActionListener(this);
        ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
        selectClassEnrolled(syId.getId());
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                quitApp();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnrolledStudents = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSchoolYear = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonRegister = new javax.swing.JButton();
        jButtonClassOffer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonClassOffer1 = new javax.swing.JButton();
        jButtonClassOffer2 = new javax.swing.JButton();
        jButtonClassOffer3 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemChangePassword = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuManage = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jTableEnrolledStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEnrolledStudents);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(1376, 5));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1376, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel10.setPreferredSize(new java.awt.Dimension(1376, 60));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jButtonNew.setIcon(new FlatSVGIcon("svg/student.svg",32,32));
        jButtonNew.setText("<html><center>Register<br>Student</center></html>");
        jButtonNew.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonNew.setPreferredSize(new java.awt.Dimension(90, 42));
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonNew);

        jPanel3.add(jPanel10, java.awt.BorderLayout.SOUTH);

        jPanel11.setPreferredSize(new java.awt.Dimension(10, 599));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel12.setPreferredSize(new java.awt.Dimension(10, 599));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(1376, 35));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(886, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 2));

        jLabel2.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel6.add(jLabel2);

        jLabel1.setText("SCHOOL YEAR:");
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 32));
        jPanel6.add(jLabel1);

        jComboBoxSchoolYear.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel6.add(jComboBoxSchoolYear);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 2));

        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel7.add(jTextFieldSearch);

        jPanel5.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(1376, 60));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(84, 60));

        jButtonRegister.setIcon(new FlatSVGIcon("svg/student.svg",56,56));
        jButtonRegister.setToolTipText("Register Student");
        jButtonRegister.setFocusable(false);
        jButtonRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegister.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonRegister.setMaximumSize(new java.awt.Dimension(58, 58));
        jButtonRegister.setMinimumSize(new java.awt.Dimension(58, 58));
        jButtonRegister.setPreferredSize(new java.awt.Dimension(58, 58));
        jButtonRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRegister);

        jButtonClassOffer.setIcon(new FlatSVGIcon("svg/class_offer.svg",56,56));
        jButtonClassOffer.setToolTipText("Class Offer");
        jButtonClassOffer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClassOffer.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonClassOffer.setMaximumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer.setMinimumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer.setPreferredSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClassOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassOfferActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClassOffer);
        jToolBar1.add(jSeparator2);

        jButtonClassOffer1.setIcon(new FlatSVGIcon("svg/teacher.svg",56,56));
        jButtonClassOffer1.setToolTipText("Instructor Class");
        jButtonClassOffer1.setFocusable(false);
        jButtonClassOffer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClassOffer1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonClassOffer1.setMaximumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer1.setMinimumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer1.setPreferredSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClassOffer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassOffer1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClassOffer1);

        jButtonClassOffer2.setIcon(new FlatSVGIcon("svg/enroll_student.svg",56,56));
        jButtonClassOffer2.setToolTipText("Enrolled Students");
        jButtonClassOffer2.setFocusable(false);
        jButtonClassOffer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClassOffer2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonClassOffer2.setMaximumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer2.setMinimumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer2.setPreferredSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClassOffer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassOffer2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClassOffer2);

        jButtonClassOffer3.setIcon(new FlatSVGIcon("svg/money.svg",56,56));
        jButtonClassOffer3.setToolTipText("Tuition Fee");
        jButtonClassOffer3.setFocusable(false);
        jButtonClassOffer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClassOffer3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonClassOffer3.setMaximumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer3.setMinimumSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer3.setPreferredSize(new java.awt.Dimension(58, 58));
        jButtonClassOffer3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClassOffer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassOffer3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClassOffer3);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(10, 45));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setPreferredSize(new java.awt.Dimension(10, 60));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jMenuUser.setText("File");

        jMenuItemChangePassword.setIcon(new FlatSVGIcon("svg/key.svg",18,18));
        jMenuItemChangePassword.setText("Change Password");
        jMenuItemChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePasswordActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemChangePassword);

        jMenuItem18.setIcon(new FlatSVGIcon("svg/logout.svg",18,18));
        jMenuItem18.setText("Logout");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem18);
        jMenuUser.add(jSeparator1);

        jMenuItem20.setIcon(new FlatSVGIcon("svg/exit.svg",18,18));
        jMenuItem20.setText("Exit");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem20);

        jMenuBar1.add(jMenuUser);

        jMenu2.setIcon(new FlatSVGIcon("svg/settings.svg",18,18));
        jMenu2.setText("Setup");

        jMenuItem1.setIcon(new FlatSVGIcon("svg/course.svg",18,18));
        jMenuItem1.setText("Course");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setIcon(new FlatSVGIcon("svg/books.svg",18,18));
        jMenuItem3.setText("Subject");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new FlatSVGIcon("svg/room.svg",18,18));
        jMenuItem4.setText("Room");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new FlatSVGIcon("svg/calendar.svg",18,18));
        jMenuItem5.setText("Day");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setIcon(new FlatSVGIcon("svg/clock.svg",18,18));
        jMenuItem6.setText("Time");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem19.setIcon(new FlatSVGIcon("svg/flag.svg",18,18));
        jMenuItem19.setText("Citizenship");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem7.setIcon(new FlatSVGIcon("svg/student.svg",18,18));
        jMenuItem7.setText("Student");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setIcon(new FlatSVGIcon("svg/teacher.svg",18,18));
        jMenuItem8.setText("Instructor");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenuManage.setIcon(new FlatSVGIcon("svg/tools.svg",18,18));
        jMenuManage.setText("Manage");

        jMenuItem2.setIcon(new FlatSVGIcon("svg/users.svg",18,18));
        jMenuItem2.setText("User");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem2);

        jMenuItem10.setIcon(new FlatSVGIcon("svg/date.svg",18,18));
        jMenuItem10.setText("Semester");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem10);

        jMenuItem11.setIcon(new FlatSVGIcon("svg/school.svg",18,18));
        jMenuItem11.setText("School Year");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem11);

        jMenuItem12.setIcon(new FlatSVGIcon("svg/money.svg",18,18));
        jMenuItem12.setText("Tuition");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem12);

        jMenuItem9.setIcon(new FlatSVGIcon("svg/role.svg",18,18));
        jMenuItem9.setText("Role");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem9);

        jMenuBar1.add(jMenuManage);

        jMenu4.setIcon(new FlatSVGIcon("svg/report.svg",18,18));
        jMenu4.setText("Reports");

        jMenuItem15.setIcon(new FlatSVGIcon("svg/curriculum.svg",18,18));
        jMenuItem15.setText("COR");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setIcon(new FlatSVGIcon("svg/class.svg",18,18));
        jMenuItem16.setText("Class Offer");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem17.setIcon(new FlatSVGIcon("svg/instructor_class.svg",18,18));
        jMenuItem17.setText("Instructor Class");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem17);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new FlatSVGIcon("svg/paint.svg",18,18));
        jMenu5.setText("Themes");

        jMenuItem13.setIcon(new FlatSVGIcon("svg/sun.svg",18,18));
        jMenuItem13.setText("Light");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setIcon(new FlatSVGIcon("svg/moon.svg",18,18));
        jMenuItem14.setText("Dark");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1392, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogCourse course = new JDialogCourse(this, true);
        course.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogSubject subject = new JDialogSubject(this, true);
        subject.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JDialogRoom room = new JDialogRoom(this, true);
        room.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JDialogDay day = new JDialogDay(this, true);
        day.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDialogTime time = new JDialogTime(this, true);
        time.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JDialogStudent student = new JDialogStudent(this, true);
        student.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JDialogInstructor instructor = new JDialogInstructor(this, true);
        instructor.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JDialogSemester semester = new JDialogSemester(this, true);
        semester.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JDialogSchoolYear sy = new JDialogSchoolYear(this, true);
        sy.setVisible(true);
        comboBoxSchoolYear();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        JDialogTuition tuition = new JDialogTuition(this, true);
        tuition.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        JDialogEnrollStudent enrollStudent = new JDialogEnrollStudent(this, true);
        enrollStudent.setVisible(true);
        ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
        selectClassEnrolled(syId.getId());
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        String text = jTextFieldSearch.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text + ",*"));
        }
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JFrameRegister.class.getName()).log(Level.SEVERE, null, ex);
            }

        });
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JFrameRegister.class.getName()).log(Level.SEVERE, null, ex);
            }

        });
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jButtonClassOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassOfferActionPerformed
        if (schoolYearDAOImpl.getCurrentSchoolYearIDAndTuitionID() == null) {
            JOptionPane.showMessageDialog(this, "Check the current school year, and the current date should match.", "WARNING!!", JOptionPane.PLAIN_MESSAGE);
            return;
        } else {
            JDialogClassOffer classOffer = new JDialogClassOffer(this, true);
            classOffer.setVisible(true);
        }
    }//GEN-LAST:event_jButtonClassOfferActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDialogUserAccount userAccount = new JDialogUserAccount(this, true);
        userAccount.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JDialogRole role = new JDialogRole(this, true);
        role.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        JDialogReportCOR cor = new JDialogReportCOR(this, true);
        cor.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JDialogReportClassOffer co = new JDialogReportClassOffer(this, true);
        co.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if (classOfferDAOImpl.getCurrentClassOfferId() <1) {
            JOptionPane.showMessageDialog(this, "No class offer to this current school year.", "WARNING!!", JOptionPane.PLAIN_MESSAGE);
            return;
        } else {
            JDialogEnrollStudent enrollStudent = new JDialogEnrollStudent(this, true);
            enrollStudent.setVisible(true);
            ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
            selectClassEnrolled(syId.getId());
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JDialogReportInstructor instructor = new JDialogReportInstructor(this, true);
        instructor.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        quitApp();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jButtonClassOffer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassOffer1ActionPerformed
        JDialogInstructorSubjects subject = new JDialogInstructorSubjects(this, true);
        subject.setVisible(true);
    }//GEN-LAST:event_jButtonClassOffer1ActionPerformed

    private void jMenuItemChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangePasswordActionPerformed
        JDialogChangePassword changePassword = new JDialogChangePassword(this, true, userAccount);
        changePassword.setVisible(true);
    }//GEN-LAST:event_jMenuItemChangePasswordActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        this.dispose();
        new AppController(new JFrameLogin());
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        JDialogCitizenship citizenship = new JDialogCitizenship(this, true);
        citizenship.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jButtonClassOffer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassOffer2ActionPerformed
        JDialogEnrolledStudents enrolledStudents = new JDialogEnrolledStudents(this, true);
        enrolledStudents.setVisible(true);
    }//GEN-LAST:event_jButtonClassOffer2ActionPerformed

    private void jButtonClassOffer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassOffer3ActionPerformed
        JDialogSchoolYearTuition syTuitionFee = new JDialogSchoolYearTuition(this, true);
        syTuitionFee.setVisible(true);
    }//GEN-LAST:event_jButtonClassOffer3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClassOffer;
    private javax.swing.JButton jButtonClassOffer1;
    private javax.swing.JButton jButtonClassOffer2;
    private javax.swing.JButton jButtonClassOffer3;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<Object> jComboBoxSchoolYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemChangePassword;
    private javax.swing.JMenu jMenuManage;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTable jTableEnrolledStudents;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
   DefaultTableModel tableModel = new DefaultTableModel(new Object[]{"#", "SURNAME", "FIRST NAME", "MIDDLE NAME", "GENDER", "COURSE", "UNITS", "TUITION FEE/UNIT", "TOTAL TUITION FEE"}, 0) {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return Integer.class;
            }
            switch (columnIndex) {
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;
                case 6:
                    return Integer.class;
                case 7:
                    return Integer.class;
                case 8:
                    return Integer.class;
                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 10) {
                return false;

            } else {
                return true;
            }
        }
    };

    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModel);

    private void setTable() {
        jTableEnrolledStudents.setCellSelectionEnabled(true);
        jTableEnrolledStudents = new JTable(tableModel);
        jScrollPane1.setViewportView(jTableEnrolledStudents);
        jTableEnrolledStudents.addMouseListener(this);
        jTableEnrolledStudents.setRowSorter(sorter);

        TableColumn[] column = new TableColumn[100];
        column[0] = jTableEnrolledStudents.getColumnModel().getColumn(0);
        column[0].setPreferredWidth(20);
        column[5] = jTableEnrolledStudents.getColumnModel().getColumn(5);
        column[5].setPreferredWidth(280);

//        TableColumn hide0 = jTableEnrolledStudents.getColumnModel().getColumn(0);
//        hide0.setMinWidth(0);
//        hide0.setMaxWidth(0);
//        hide0.setPreferredWidth(0);
    }

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private void comboBoxSchoolYear() {
        schoolYearDAOImpl.comboBoxSchoolYear();
        jComboBoxSchoolYear.removeAllItems();
        for (ComboBoxList a : schoolYearDAOImpl.getList()) {
            this.jComboBoxSchoolYear.addItem(a);
        }
    }
    private ArrayList<ClassEnroll> classEnrollList;

    private void selectClassEnrolled(Long syID) {
//"#","FIRST NAME","MIDDLE NAME","SURNAME","GENDER","COURSE","UNITS","TUITION FEE/UNIT","TOTAL TUITION FEE"
        tableModel.setRowCount(0);
        classEnrollList = classEnrollDAOImpl.selectClassEnroll(syID);
        tableModel.setRowCount(0);
        for (ClassEnroll ce : classEnrollList) {
            tableModel.addRow(new Object[]{jTableEnrolledStudents.getRowCount() + 1, ce.getStudent().getSurname(), ce.getStudent().getFirstname(), ce.getStudent().getMiddlename(), ce.getStudent().getGender(), ce.getClassOffer().getCourse().getCourse(),
                ce.getClassOffer().getSubject().getUnit(), df.format(ce.getClassOffer().getSchoolYear().getTuition().getTuitionFee()), df.format(ce.getClassOffer().getSubject().getUnit() * ce.getClassOffer().getSchoolYear().getTuition().getTuitionFee())});
        }

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            if (e.getSource() == jComboBoxSchoolYear) {
                ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
                selectClassEnrolled(syId.getId());
            }
        } catch (Exception ex) {

        }
    }

    private void quitApp() {
        try {
            int reply = JOptionPane.showConfirmDialog(this,
                    "Are you sure to exit ARegister application?",
                    "ARegister - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                System.exit(0);        //Close the Application.
            } else if (reply == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @return the jMenuManage
     */
    public javax.swing.JMenu getjMenuManage() {
        return jMenuManage;
    }

    /**
     * @param jMenuManage the jMenuManage to set
     */
    public void setjMenuManage(javax.swing.JMenu jMenuManage) {
        this.jMenuManage = jMenuManage;
    }

}
